"""create assessments table

Revision ID: 3c6d7526617b
Revises:
Create Date: 2026-07-05 10:46:18.502790

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c6d7526617b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("project_name", sa.String(length=255), nullable=False),
        sa.Column("overall_risk_level", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("input_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessments_created_at"), "assessments", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_assessments_id"), "assessments", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assessments_id"), table_name="assessments")
    op.drop_index(op.f("ix_assessments_created_at"), table_name="assessments")
    op.drop_table("assessments")
    # ### end Alembic commands ###
