"""add archived flag to assessments

Revision ID: fc467b4eaec3
Revises: d06d67a56883
Create Date: 2026-07-20 13:08:08.944820

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc467b4eaec3"
down_revision: str | Sequence[str] | None = "d06d67a56883"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default fills existing rows; it is dropped immediately afterwards
    # so the column's value comes from the model, not the database.
    op.add_column(
        "assessments",
        sa.Column(
            "archived",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column("assessments", "archived", server_default=None)
    op.create_index(
        op.f("ix_assessments_archived"), "assessments", ["archived"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assessments_archived"), table_name="assessments")
    op.drop_column("assessments", "archived")
    # ### end Alembic commands ###
